# permissions for end users to edit dexclients.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: yado
    app.kubernetes.io/managed-by: kustomize
  name: dexclient-editor-role
rules:
- apiGroups:
  - dex.capercode.eu
  resources:
  - dexclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.capercode.eu
  resources:
  - dexclients/status
  verbs:
  - get
