---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dex.caprisys.eu
  resources:
  - dexclients
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dex.caprisys.eu
  resources:
  - dexclients/finalizers
  verbs:
  - update
- apiGroups:
  - dex.caprisys.eu
  resources:
  - dexclients/status
  verbs:
  - get
  - patch
  - update
