apiVersion: dex.capercode.eu/v1alpha1
kind: DexClient
metadata:
  name: dex-test-client
spec:
  name: "dex-test-client"
  secretName: "dex-client-secret"
  redirectURIs:
  - "https://client.example.com/callback"
  trustedPeers:
  - "myfriend"
  logoURL: "https://example.com/logo.jpg"
  public: false
